config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'products#index'

  resource :cart, only: [:show]

  resources :news, only: [:index]

  resources :products

  resources :order_items do
    resources :orders
  end

end

app/models/account.rb
class Account < ApplicationRecord
  has_one :user  
  has_many :orders
  # belongs_to :user
  # , index: { unique: true }, foreign_key: true
end

app/models/accounts.rb
class Account < ApplicationRecord
  has_many :orders
  belongs_to :user
  # , index: { unique: true }, foreign_key: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :update_total
  before_create :update_status

  def calculate_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  private

  def update_status
    if self.status == nil?
      self.status = "In progress"
    end
  end

  def update_total
    self.total_price = calculate_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items

end

app/models/user.rb
class User < ApplicationRecord
  # has_one :account

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         after_create :create_account

         private

         def create_account
           @user = User.last
           account = Account.new
           account.user_id = @user.id
           account.save
         end         
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      flash[:notice] = "You've successfully signed up!"
      session[:account_id] = @account.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

  def show
    @order_items = current_order.order_items
  end



  private

  def account_params
    params.require(:account).permit(:display_name, :email, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order
  helper_method :current_account



  def current_account
    if session[:account_id]
      @current_account = Account.find(session[:account_id])
    end
  end



  def current_order
    if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/books_controller.rb
class BookController < ApplicationController
  def index
    @books = Book.get_books
  end

  def show
    @order_items = current_order.order_items
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def index
    @order_items = OrderItem.all
    render :index
  end

  def show
    @order_items = current_order.order_items
  end  

  @order_items = OrderItem.all
  @order_item = OrderItem.new

  def new
    @order_item = OrderItem.new
    render :new
  end

  def update
    @item = OrderItem.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "Order \##{@item.id} was successfully updated!"
      redirect_to cart_path
    else
      render :edit
    end
  end

  def edit
    @order_items = OrderItem.all
    @item = OrderItem.find(params[:id])
    render :edit
  end
  # def edit
  #   @user = User.find(params[:id])
  # end
  def create
    @order = current_order
    @item = @order.order_items.new(item_params)
    @order.save
    session[:order_id] = @order.id
    redirect_to products_path
  end

  def destroy
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.destroy
    @order.save
    redirect_to cart_path
  end

  private

  def item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    @order_items = OrderItem.all
    @order_item = current_order.order_items.new
  end

  def product_params
    params.require(:product).permit(:name, :price)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render :index
  end

  def show
    @order_items = current_order.order_items
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/_form.html.erb
<%= form_for @order_item do |f| %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.submit %>
<% end %>

app/views/carts/show.html.erb
<% if @order_items.any? %>
  <% @order_items.order("id asc").each do |item| %>
    <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"} %></p>
    <p> Unit Price: <%= number_to_currency item.product.price %>
      <!-- <%= link_to "Edit", edit_order_item_path(item) %> -->
      <%= render "layouts/errors", :object => @order_items %>

      <%= form_for item do |f| %>
        <%= f.label :quantity %>
        <%= f.text_field :quantity %>
        <%= f.submit %>
      <% end %>


       | Total Price: <%= number_to_currency (item.product.price * item.quantity) %></p>
  <% end %>
  <p>Your Total: <%= number_to_currency current_order.total_price %></p>
<% else %>
  <p>Your shopping cart is empty.</p>
<% end %>

<%= link_to "Return to Product List", products_path %>

app/views/layouts/_navbar.html.erb
<header>
  <nav>
    <div class="container textalign">
      <div class="col-md-6">
        <!-- <ul class="cap"> -->
        <span><a href="/" class="specialColor">Home</a></span>
        <a><%= link_to "New Order Item", new_order_item_path() %></a>
        <span><a href="">Placeholder2</a></span>
        <span><a href="">Placeholder3</a></span>
        <span class="nav-sprite"></span>
        <!-- </ul> -->
        <% if current_user %>
          <%= link_to "Sign out", '/users/sign_out', method: 'delete' %> |
          <%=link_to "Hi, #{current_user.email}", '/' %> |
          <%=link_to "Edit user", '/users/edit' %>
          <a href="/cart">

            <div class="countingItems">
              <%itemCount = 0%>
              <!--where userid = to those items-->
              <% @order_items.length do |item| %>
                <%if (@order_items.id != 1)%>
                  <%itemCount = itemCount + 1%>
                <%end%>
              <%end%>
                <%if (request.fullpath=="/")%><%itemCount = itemCount-1%><%end%>
                <%=@order_items.length%>

            </div>

          </a>
        <% else %>
          <%= link_to "Sign in", '/users/sign_in' %>
          <%= link_to "Sign up", '/users/sign_up' %>
        <% end %>
      </div>

    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EPI-CART</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <center class="destroyed">
      <%= flash[:alert] %>
      <%= flash[:notice] %>
    </center>
    <%= render 'layouts/navbar' %>
      <%= yield %>
  </body>
</html>

app/views/order_items/_form.html.erb
<%= render "layouts/errors", :object => @order_items %>

<%= form_for @item do |f| %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.submit %>
<% end %>

app/views/order_items/edit.html.erb
<div class="container" class="form-fields">
  <h1>Edit Cart Item</h1>


  <%= render "form" %>
</div>

app/views/order_items/new.html.erb
<%= form_for @order_item, url: product_path, html: { multipart: true } do |f| %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/order_items/show.html.erb
<h1>HELLO</h1>

app/views/products/_form.html.erb
<%= render "layouts/error", :object => @product %>

<%= form_for @product, url: products_path, html: { multipart: true } do |f| %>
  <%= f.label :picture %>
  <%= f.file_field :picture %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/products/index.html.erb
<h1 class="textalign">Products</h1>

<!-- Product.create!(name: Faker::Vehicle.manufacture,
                      price: Faker::Number.decimal(2))
                      @product_id = Product.last.id -->


<div class="container">
  <% @products.each do |product| %>
  <%= product.name %> | <%= number_to_currency product.price %>
    <%= form_for @order_item do |f| %>
    <%= f.hidden_field :product_id, value: product.id %>
    <%= f.number_field :quantity %>
    <%= f.submit "Add to cart" %>
    <% end %></p>
    <% end %>
</div>

app/views/products/show.html.erb
<h1>SHOW PRODUCT</h1>